### ISSUE TITLE
Decoder might block if there is data remaining to be flushed from the codec and the stream blocks

### ISSUE THREAD

**Issue by Nemo157** [Nullus157/async-compression#123]
See https://github.com/gyscos/zstd-rs/issues/119, I'm pretty sure the local `bufread::Decoder` implementations suffer from this same issue. My first attempt at writing a test case failed to fail though.

**Comment by nl5887** [comment]
I encountered this issue when keeping an open connection, while not sending data. This caused the remaining data to be kept in the decoder. I have fixed the issue, but will try to write a test case.

**Comment by fr3akX** [comment]
could you, please, review and merge this PR?
