### ISSUE TITLE
Make nightly build test against updated dependencies

### ISSUE THREAD

**Issue by Nemo157** [Nullus157/async-compression#124]
#122 should have been picked up automatically when zstd 0.8.2 was released; there should be another job that runs nightly (but using the stable compiler), updates all dependencies, then runs the tests, and opens an issue if there is a failure.

**Comment by Xuanwo** [comment]
> there should be another job that runs nightly (but using the stable compiler), updates all dependencies, then runs the tests, and opens an issue if there is a failure.

Maybe we can use `dependabot`.

**Comment by robjtede** [comment]
at some point stopped tracking the lockfile, so nightly job runs will catch these issues now
