### ISSUE TITLE
Please support enabling zstd long-distance matching mode

### ISSUE THREAD

**Issue by joshtriplett** [Nullus157/async-compression#133]
async-compression only allows passing a numeric level. I'd love to enable the zstd "long-distance matching mode", which substantially improves compression on large files that may have similarity at long distances.

I'd be happy to supply a PR implementing this. Would you prefer to extend `Level` to contain internal flags for things like this, or would you prefer to add a method (or additional constructor) directly to the `ZstdEncoder` to set this parameter?

**Comment by joshtriplett** [comment]
I submitted https://github.com/Nemo157/async-compression/pull/134 implementing this. (Happy to take a different approach if you would prefer.)

**Comment by Nemo157** [comment]
Unfortunately I want to keep the algorithmic dependencies of `async-compression` private to allow non-breaking updates.

I have long been meaning to split out the underlying generic implementation that exposes these and would allow full configurability for different libraries, with the downside of needing to either support multiple implementations/versions of the algorithms or doing breaking releases.

I think I had started an attempt at that a while ago, but found it less trivial than I was hoping. This is some motivation to look at it again, hopefully I can at least see how difficult it appears this weekend.

**Comment by joshtriplett** [comment]
Would you consider a PR adding an abstraction over a handful of the options, to avoid exposing the underlying library? I'd be happy to prepare such a patch.

**Comment by joshtriplett** [comment]
This is now fixed, with #134.
