### ISSUE TITLE
not all ZStd compression levels are usable

### ISSUE THREAD

**Issue by H4xX0r1337** [Nullus157/async-compression#179]
the quality level of zstd is mapped like this `quality.min(21) as i32`. ZStd goes up to level 22, which is unreachable.
Another issue that is probably a bit harder to fix is the fact that the compression levels of zstd start at -7, while `Level::Precise` uses an `u32` for representing levels.
maybe it would be appropriate to bump the major version and swap the `u32` with an `i32` (or maybe even an `i16`, i doubt level 10000 would be surpassed by any algorithm)

**Comment by zamazan4ik** [comment]
@Nemo157 what do you think about the issue?

**Comment by Nemo157** [comment]
[The docs](https://docs.rs/zstd/latest/zstd/stream/write/struct.Encoder.html#method.new) say the range is `1-21` and `0` uses the default (not the exact type used, but the `level` flows into the same place so the docs should all be equivalent).

**Comment by Nemo157** [comment]
Those docs may be out of date given <https://docs.rs/zstd/latest/zstd/fn.compression_level_range.html> exists and gives `-131072..=22` for me. It would be easy to at least use the upper bound from that, changing the lower bound would take a breaking change.

**Comment by gaby** [comment]
@Nemo157 Would it be possible to upgrade to zstd 1.5.5, there's a data corruption fix that was released with that version

Rel #187
