### ISSUE TITLE
with_quality_and_params and ZStandard

### ISSUE THREAD

**Issue by Smotrov** [Nullus157/async-compression#231]
new function `async_compression::tokio::write::ZstdEncoder::with_quality_and_params` is panic with such code

```
    let mut zstd_encoder = async_compression::tokio::write::ZstdEncoder::with_quality_and_params(
        Vec::new(),
        async_compression::Level::Precise(9),
        &[async_compression::zstd::CParameter::nb_workers(10)]
    );
```
There is an ugly unwrap() inside. 
because zstd requires zstdmt feature to run multi core. 

To workaround you can add this line to cargo.toml

`zstd = { version = "0.12.3", features = ["zstdmt"] }`

**Comment by NobodyXu** [comment]
IMO there are several ways to fix this:
 - Enable `zstd/zstdmt` by default
 - Add a new feature which enables `zstd/zstdmt`
 - Call `Encoder::set_parameter` lazily on write

**Comment by robjtede** [comment]
> Add a new feature which enables zstd/zstdmt
> second one is breaking change

Not necessaryily. Adding a new feature to forward `zstdmt` is fine. And we can document that the `nb_workers` fn _needs_ the new crate feature without actually requiring it until the next breaking update.
