### ISSUE TITLE
Brotli encoder parameters

### ISSUE THREAD

**Issue by Smotrov** [Nullus157/async-compression#239]
It would be beneficial to implement additional Brotli encoder parameters, such as lgwin and size_hint, beyond just the quality parameter.

**Comment by NobodyXu** [comment]
I am willing to review and merge PR adding support for that.
I am quite busy recently so I might not have time to do this.

**Comment by Smotrov** [comment]
One question: how to create an instance of `async_compression::brotli::EncoderParams` if all fields are private and all methods requires `self`?
