### ISSUE TITLE
Support Decoding Block GZIP?

### ISSUE THREAD

**Issue by tshauck** [Nullus157/async-compression#260]
Hi,

I've noticed that when trying to use the gzip decoder to decode [bgzip][], the decoder will work up to the first block end, then return rather than reading to the end. See the example below, but I'm curious what the stance of this library is for support decoding bgzip files?

The compression is nothing more than concatenated gzip blocks and thought to be compatible for decompression (e.g. `gzcat` works), but there's edge cases (e.g. like this library).

I'd be happy to take a look unless, but I didn't want to implement something here (vs higher up the stack) if there were other thoughts. Thanks!

Example:

If I make an `example.bgz` (e.g. just a text file that's a 1mb or so), then use it with this code, the length is only the first block... `Decompressed data length: 65277`.

```rust
use async_compression::tokio::bufread::GzipDecoder;
use tokio::fs::File;
use tokio::io::{self, AsyncReadExt, BufReader};

#[tokio::main]
async fn main() -> io::Result<()> {
    println!("Starting decompression...");

    // Open the file
    let file = File::open("example.bgz").await?;
    let reader = BufReader::new(file);

    // Create a Gzip decoder
    let mut decoder = GzipDecoder::new(reader);

    // Prepare a buffer to store decompressed data
    let mut decompressed_data = Vec::new();

    // Read and decompress the data
    decoder.read_to_end(&mut decompressed_data).await?;

    // Get the length of the decompressed data
    let len = decompressed_data.len();

    // Print the length of the decompressed data
    println!("Decompressed data length: {}", len);

    // Print the last 100 bytes of the decompressed data under a lossy UTF-8 encoding
    println!(
        "Decompressed data: {:?}",
        String::from_utf8_lossy(&decompressed_data[len - 100..])
    );

    Ok(())
}
```

[bgzip]: https://www.htslib.org/doc/bgzip.html

**Comment by Nemo157** [comment]
There's a flag to enable this behavior on all decoders: https://docs.rs/async-compression/latest/async_compression/tokio/bufread/struct.GzipDecoder.html#method.multiple_members

**Comment by tshauck** [comment]
That's great, I'll close this and work my way up then. Thanks!
