### ISSUE TITLE
Wrapping an `AsyncRead + AsyncWrite` stream

### ISSUE THREAD

**Issue by link2xt** [Nullus157/async-compression#296]
I have a `AsyncRead + AsyncWrite` network stream that I want to compress, like a [`TcpStream`](https://docs.rs/tokio/latest/tokio/net/struct.TcpStream.html) or [`TlsStream`](https://docs.rs/tokio-rustls/latest/tokio_rustls/client/struct.TlsStream.html).

Is there a way to wrap such stream to get a single `CompressedStream` with `async-compress`?

If I use [`tokio::io::split`](https://docs.rs/tokio/latest/tokio/io/fn.split.html) and then wrap each part in e.g. `DeflateEncoder` and `DeflateDecoder` separately, I get two separate objects and not a single stream anymore. Besides, `split` adds overhead by placing the inner stream behind a mutex. In https://github.com/async-email/async-imap/pull/112 I manually placed the stream behind a mutex to pass it into `DeflateEncoder` and `DeflateDecoder`, so at least I have an access to inner stream, but now I cannot have a `get_ref()` and `get_mut()` API on the resulting stream because it is behind a mutex internally.

What I want is some API like a compressed stream builder which gets encoder, decoder and underlying stream and constructs a single object that allows direct access to underlying stream via `get_ref()` and `get_mut()`. Is it impossible with `async-compression`?

**Comment by NobodyXu** [comment]
You can use [`TcpStream::into_split`](https://docs.rs/tokio/latest/tokio/net/struct.TcpStream.html#method.into_split), which is reversible.

**Comment by NobodyXu** [comment]
cc @link2xt how about `TcpStream::into_split`?

Can it solve your problem efficiently?

**Comment by NobodyXu** [comment]
> This works if you have plain `TcpStream`, but in deltachat-core-rust I have `TlsStream<TcpStream>>` or `TlsStream<Socks5Stream<TcpStream>>` or some other encrypted and proxified streams that don't have `into_split()`.

Can you call `TcpStream::into_split` before creating `TlsStream`?

Or, can you pass a reference to the `*Decoder::new` method?

**Comment by NobodyXu** [comment]
> In async-imap I even have just `AsyncRead + AsyncWrite` stream without any assumptions about the underlying stream,

Hmmm I was mostly worried about having mismatched functionality, since `bufread` type should be `AsyncBufRead`.

But then I realized that if we consider async-compression to be a decorator that adds a layer to decompress/compress, it does make sense

**Comment by NobodyXu** [comment]
Yeah it does seem to be a reasonable pattern.

The buf reader/tls/compress/decompress can be seen as an decorator, so they should pass through everything trait that isn't decorated.
