### ISSUE TITLE
Gzip compression level 0

### ISSUE THREAD

**Issue by eth3lbert** [Nullus157/async-compression#313]
Currently, the compression level for Gzip is clamped between 1 (fast) and 9 (best). However, level 0 is supported by the flate2 crate and Python's gzip module. While changing the level range could be a breaking change, are there any alternative approaches to address this issue? For example, introducing a `none` level might be a viable solution?

**Comment by NobodyXu** [comment]
I think that you can use`Level::Precise(0)`?

The problem though is that we clamp it based on min/max supported by flate2

https://docs.rs/async-compression/latest/src/async_compression/lib.rs.html#216

And flate2 fastest uses compression level 1

https://docs.rs/flate2/latest/src/flate2/lib.rs.html#218-220

**Comment by NobodyXu** [comment]
Yes and that is because `flate2::Compression::fast()` uses level 1.

I believe it's better to update flate2 to use level 0?

**Comment by eth3lbert** [comment]
Yeah, it would be great the `Precise` part could be changed to something similar to:
```rust
            Self::Precise(quality) => flate2::Compression::new(
                quality
                    .try_into()
                    .unwrap_or(0)
                    .clamp(flate2::Compression::none(), best.level()),
            ),
```

**Comment by NobodyXu** [comment]
Hmmm I think this makes sense to make.

I would accept a PR for this.
