### ISSUE TITLE
Add `http-body` support

### ISSUE THREAD

**Issue by LucioFranco** [Nullus157/async-compression#33]
I'd like to introduce [`http-body`](https://docs.rs/http-body) support to `async-compression` under a feature flag. This feature would provide a [`Body`](https://docs.rs/http-body/0.2.0-alpha.1/http_body/trait.Body.html) type that wraps another body type and will compress each chunk of data pulled from the body. This is to allow things like a tower service that can compress an entire http request via `Content-Type`.

cc @Nemo157

**Comment by Nemo157** [comment]
Similar to the current `stream` support, it seems likely that `http-body` can use general buffered async IO adapters to fit into the standard `impl AsyncBufRead -> impl AsyncRead` that `async-compression` provides. Given the deprecation of `stream` in 0.3.8 I think it'd make sense to not actually implement any support here, but maybe provide an example of the most appropriate adapters to use.
